language: scala

scala:
  - 2.10.7
  - 2.11.12
  - 2.13.1

env: ADOPTOPENJDK=11

matrix:
  include:
  - env: ADOPTOPENJDK=8
    scala: 2.12.11
  - env: ADOPTOPENJDK=11
    scala: 2.12.11
    script:
      - sbt ++$TRAVIS_SCALA_VERSION! "test" "mimaReportBinaryIssues"
      - sbt ++$TRAVIS_SCALA_VERSION! "benchmark/jmh:run -i 10 -wi 3 -f1 -t1"

script: sbt ++$TRAVIS_SCALA_VERSION! "test"

before_install:
  # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
  - "[[ -d $HOME/.sdkman/bin/ ]] || rm -rf $HOME/.sdkman/"
  - curl -sL https://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"

install:
  - sdk install java $(sdk list java | grep -o "$ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1)
  - unset JAVA_HOME
  - java -Xmx32m -version
  - javac -J-Xmx32m -version

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.sbt/boot
    - $HOME/.sdkman
